### ISSUE TITLE
examples里的子项目报eslint的错误. 我确定eslint都是被安装过的

### ISSUE THREAD

**Issue by mayunxuan** [F-loat/vue-cli-plugin-qiankun#12]
Module build failed (from ./node_modules/eslint-loader/index.js):
[1] Error: No ESLint configuration found.
[1]     at Config.getLocalConfigHierarchy (H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\eslint\lib\config.js:268:39)
[1]     at Config.getConfigHierarchy (H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\eslint\lib\config.js:192:43)
[1]     at Config.getConfigVector (H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\eslint\lib\config.js:299:21)
[1]     at Config.getConfig (H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\eslint\lib\config.js:342:29)
[1]     at processText (H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\eslint\lib\cli-engine.js:181:33)
[1]     at CLIEngine.executeOnText (H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\eslint\lib\cli-engine.js:690:40)
[1]     at lint (H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\eslint-loader\index.js:278:17)
[1]     at transform (H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\eslint-loader\index.js:252:18)
[1]     at H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\loader-fs-cache\index.js:127:18
[1]     at ReadFileContext.callback (H:\ceshi\vue-cli-plugin-qiankun\examples\foo-app\node_modules\loader-fs-cache\index.js:31:14)
[1]     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:239:13)

**Comment by F-loat** [comment]
我这边没有出现这个问题，重新安装依赖看看？

``` sh
cd examples
yarn
yarn install:all
yarn serve:all
```

**Comment by F-loat** [comment]
或者你有修改过什么吗
